let i = 10;
let f = 20.5;
let b = true;
let s = "Ha Noi";
document.write('i = ' + i);
document.write('<br/>');
document.write('f = ' + f);
document.write('<br/>');
document.write('b = ' + b);
document.write('<br/>');
document.write('s = ' + s);
document.write('<br/>');
let width = 10;
let height = 20;
let area = width * height;
document.write('area = ' + area);
